-- VirtuWill data model · fitness: one base table for every workout, a fact table per kind
--
--   fitness.categories       cardio · strength (lifting) · hiit · mobility (yoga) · other
--   fitness.activity_types   what was done: run, walk, dog walk, bike … each in one category,
--                            and whether it counts toward the workout goal (a dog walk doesn't)
--   fitness.workouts         one row per session, whatever its kind: date, activity, minutes, note, source
--   fitness.workout_cardio   1:1 for cardio: distance, climbing, calories, heart rate
--   fitness.workout_routes   1:1 with a cardio row: the GPS line, from a GPX/TCX file or RunKeeper
--   fitness.workout_strength one row per lift: sets (reps and weight when known)
--   fitness.workout_hiit     1:1 for HIIT: the circuit
--   fitness.workout_sessions the view the screens and the API read: a workout with all of its facts
--
-- Each fact table carries its category and points at (workout_id, category), so a cardio row can
-- only belong to a cardio workout. A workout's category follows its activity type, and changing
-- the activity to another category drops the old kind's facts (fitness.workouts_category trigger).
--
-- This replaces journal.workouts (with workout_types, workout_routes, workout_lifts and
-- workout_circuits), whose rows move here with the same ids. Its free-text activity
-- ("Running", "Bike") becomes an activity type (fitness.activity_type_for), and is kept as the title.

CREATE SCHEMA IF NOT EXISTS fitness;

CREATE TABLE IF NOT EXISTS fitness.categories (
    category TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    position INTEGER NOT NULL
);
INSERT INTO fitness.categories VALUES ('cardio', 'Cardio', 10), ('strength', 'Lifting', 20), ('hiit', 'HIIT', 30),
                                      ('mobility', 'Yoga & mobility', 40), ('other', 'Other', 50)
ON CONFLICT (category) DO NOTHING;

CREATE TABLE IF NOT EXISTS fitness.activity_types (
    activity_type TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    category TEXT NOT NULL REFERENCES fitness.categories,
    counts_toward_goal BOOLEAN NOT NULL DEFAULT true,     -- a dog walk is logged but never qualifies a day
    position INTEGER NOT NULL DEFAULT 100,
    UNIQUE (activity_type, category)
);
INSERT INTO fitness.activity_types (activity_type, label, category, counts_toward_goal, position) VALUES
    ('run', 'Run', 'cardio', true, 10), ('walk', 'Walk', 'cardio', true, 20), ('dog_walk', 'Dog walk', 'cardio', false, 30),
    ('bike', 'Bike', 'cardio', true, 40), ('hike', 'Hike', 'cardio', true, 50), ('swim', 'Swim', 'cardio', true, 60),
    ('row', 'Row', 'cardio', true, 70), ('elliptical', 'Elliptical', 'cardio', true, 80), ('ski', 'Ski', 'cardio', true, 90),
    ('cardio', 'Other cardio', 'cardio', true, 99),
    ('strength', 'Lifting', 'strength', true, 10),
    ('hiit', 'HIIT', 'hiit', true, 10),
    ('yoga', 'Yoga', 'mobility', true, 10), ('mobility', 'Mobility / recovery', 'mobility', true, 20),
    ('other', 'Other', 'other', true, 10)
ON CONFLICT (activity_type) DO NOTHING;

-- The activity type for a workout described the older way: its type (Strength, Cardio, HIIT, Mobility / recovery,
-- Dog walk, Other) and what it was ("Running", "Bike", RunKeeper's "Strength Training"). The type decides where it
-- can; otherwise the words do, matched at the start of a word ("brunch" is not a run). Used by this file's move,
-- and by the app for RunKeeper and the Health tracker, so the rules live in one place.
CREATE OR REPLACE FUNCTION fitness.activity_type_for(kind TEXT, what TEXT) RETURNS TEXT
LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE
        WHEN kind = 'Dog walk' THEN 'dog_walk'
        WHEN kind = 'Strength' THEN 'strength'
        WHEN kind = 'HIIT' THEN 'hiit'
        WHEN kind = 'Mobility / recovery' THEN CASE WHEN what ~* '\myoga' THEN 'yoga' ELSE 'mobility' END
        WHEN what ~* '\mdog' AND what ~* '\mwalk' THEN 'dog_walk'
        WHEN what ~* '\m(run|jog)' THEN 'run'
        WHEN what ~* '\m(bik|cycl|ride|spin)' THEN 'bike'
        WHEN what ~* '\mhik' THEN 'hike'
        WHEN what ~* '\mswim' THEN 'swim'
        WHEN what ~* '\mrow' THEN 'row'
        WHEN what ~* '\mellip' THEN 'elliptical'
        WHEN what ~* '\mwalk' THEN 'walk'
        WHEN what ~* '\m(ski|snowboard)' THEN 'ski'
        WHEN what ~* '\m(strength|weight|lift)' THEN 'strength'
        WHEN what ~* '\m(hiit|circuit|crossfit|bootcamp|boxing)' THEN 'hiit'
        WHEN what ~* '\myoga' THEN 'yoga'
        WHEN what ~* '\m(pilates|stretch|mobility|meditat)' THEN 'mobility'
        WHEN kind = 'Cardio' OR what ~* '\m(cardio|stair|arc trainer|danc|zumba|barre|skat)' THEN 'cardio'
        ELSE 'other'
    END
$$;

CREATE TABLE IF NOT EXISTS fitness.workouts (
    workout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_date DATE NOT NULL REFERENCES core.calendar (day),
    started_at TIMESTAMPTZ,
    activity_type TEXT NOT NULL,
    category TEXT NOT NULL,                 -- the activity type's; set by fitness.workouts_category
    title TEXT NOT NULL DEFAULT '',         -- a name of your own ("Long run"); the activity's label otherwise
    minutes NUMERIC CHECK (minutes IS NULL OR minutes BETWEEN 0 AND 1440),
    note TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL CHECK (source IN ('manual', 'journal', 'health_tracker', 'runkeeper')),
    source_ref TEXT,
    details JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workout_id, category),
    FOREIGN KEY (activity_type, category) REFERENCES fitness.activity_types (activity_type, category) ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS workouts_by_date ON fitness.workouts (workout_date);
CREATE INDEX IF NOT EXISTS workouts_by_source ON fitness.workouts (source, workout_date);
-- An imported record keeps its row (and id) across loads.
CREATE UNIQUE INDEX IF NOT EXISTS workouts_by_tracker_ref ON fitness.workouts (source_ref) WHERE source = 'health_tracker';
CREATE UNIQUE INDEX IF NOT EXISTS workouts_by_runkeeper_ref ON fitness.workouts (source_ref) WHERE source = 'runkeeper';

CREATE TABLE IF NOT EXISTS fitness.workout_cardio (
    workout_id BIGINT PRIMARY KEY,
    category TEXT NOT NULL DEFAULT 'cardio' CHECK (category = 'cardio'),
    distance NUMERIC CHECK (distance IS NULL OR distance BETWEEN 0 AND 1000),
    distance_unit TEXT NOT NULL DEFAULT 'mi' CHECK (distance_unit IN ('mi', 'km')),
    -- The canonical distance for every calculation; distance and distance_unit keep what was entered.
    distance_km NUMERIC GENERATED ALWAYS AS (CASE distance_unit WHEN 'mi' THEN distance * 1.609344 ELSE distance END) STORED,
    elevation_gain_m NUMERIC,
    calories NUMERIC CHECK (calories IS NULL OR calories >= 0),
    avg_heart_rate NUMERIC CHECK (avg_heart_rate IS NULL OR avg_heart_rate BETWEEN 20 AND 250),
    FOREIGN KEY (workout_id, category) REFERENCES fitness.workouts (workout_id, category) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fitness.workout_routes (
    workout_id BIGINT PRIMARY KEY REFERENCES fitness.workout_cardio ON DELETE CASCADE,
    points JSONB NOT NULL CHECK (jsonb_typeof(points) = 'array'),   -- [[lat, lng], …], simplified for drawing
    distance_km NUMERIC,                                            -- measured along the full track
    elevation_gain_m NUMERIC,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    file_name TEXT NOT NULL DEFAULT '',
    file_asset_id BIGINT REFERENCES core.media_assets ON DELETE SET NULL,   -- an uploaded file; RunKeeper's stay in bronze
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The lifts to pick from move with the workouts.
DO $$ BEGIN
    IF to_regclass('fitness.lifts') IS NULL AND to_regclass('journal.lifts') IS NOT NULL THEN
        ALTER TABLE journal.lifts SET SCHEMA fitness;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS fitness.workout_strength (
    workout_id BIGINT NOT NULL,
    category TEXT NOT NULL DEFAULT 'strength' CHECK (category = 'strength'),
    position INTEGER NOT NULL,
    lift TEXT NOT NULL REFERENCES fitness.lifts ON UPDATE CASCADE,
    sets INTEGER NOT NULL CHECK (sets BETWEEN 1 AND 50),
    reps INTEGER CHECK (reps IS NULL OR reps BETWEEN 1 AND 1000),
    weight_lb NUMERIC CHECK (weight_lb IS NULL OR weight_lb BETWEEN 0 AND 2000),
    PRIMARY KEY (workout_id, position),
    UNIQUE (workout_id, lift),
    FOREIGN KEY (workout_id, category) REFERENCES fitness.workouts (workout_id, category) ON DELETE CASCADE
);

-- Its length is rounds × (exercises × work + (exercises − 1) × exercise rest) + (rounds − 1) × round rest.
CREATE TABLE IF NOT EXISTS fitness.workout_hiit (
    workout_id BIGINT PRIMARY KEY,
    category TEXT NOT NULL DEFAULT 'hiit' CHECK (category = 'hiit'),
    rounds INTEGER NOT NULL CHECK (rounds BETWEEN 1 AND 100),
    exercises_per_round INTEGER NOT NULL CHECK (exercises_per_round BETWEEN 1 AND 50),
    work_seconds INTEGER NOT NULL CHECK (work_seconds BETWEEN 1 AND 3600),
    exercise_rest_seconds INTEGER NOT NULL DEFAULT 0 CHECK (exercise_rest_seconds BETWEEN 0 AND 3600),
    round_rest_seconds INTEGER NOT NULL DEFAULT 0 CHECK (round_rest_seconds BETWEEN 0 AND 3600),
    total_seconds INTEGER GENERATED ALWAYS AS (
        rounds * (exercises_per_round * work_seconds + (exercises_per_round - 1) * exercise_rest_seconds)
        + (rounds - 1) * round_rest_seconds) STORED,
    FOREIGN KEY (workout_id, category) REFERENCES fitness.workouts (workout_id, category) ON DELETE CASCADE
);

-- A workout's category is its activity type's. When the activity moves to another category, the old kind's
-- facts go first (a run's distance means nothing on a lifting session), so the foreign keys always hold.
CREATE OR REPLACE FUNCTION fitness.workouts_category() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.category := (SELECT category FROM fitness.activity_types WHERE activity_type = NEW.activity_type);
    IF NEW.category IS NULL THEN
        RAISE EXCEPTION 'Unknown activity type: %', NEW.activity_type USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        NEW.updated_at := now();
        IF NEW.category IS DISTINCT FROM OLD.category THEN
            DELETE FROM fitness.workout_cardio WHERE workout_id = OLD.workout_id;
            DELETE FROM fitness.workout_strength WHERE workout_id = OLD.workout_id;
            DELETE FROM fitness.workout_hiit WHERE workout_id = OLD.workout_id;
        END IF;
    END IF;
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS workouts_category ON fitness.workouts;
CREATE TRIGGER workouts_category BEFORE INSERT OR UPDATE ON fitness.workouts
    FOR EACH ROW EXECUTE FUNCTION fitness.workouts_category();

-- ── The move from journal.workouts (same ids) ───────────────────────────────
DO $$ BEGIN
    IF to_regclass('journal.workouts') IS NULL THEN
        RETURN;
    END IF;
    INSERT INTO fitness.workouts (workout_id, workout_date, started_at, activity_type, title, minutes, note, source,
                                  source_ref, details, created_at)
    SELECT w.workout_id, w.workout_date, r.started_at,
           fitness.activity_type_for(w.workout_type, COALESCE(w.details #>> '{runkeeper,type}', w.activity)),
           w.activity, w.minutes, w.note, w.source, w.source_ref, w.details, w.created_at
    FROM journal.workouts w LEFT JOIN journal.workout_routes r USING (workout_id)
    ON CONFLICT (workout_id) DO NOTHING;

    -- Every cardio workout has its cardio row, with what was known of it.
    INSERT INTO fitness.workout_cardio (workout_id, distance, distance_unit, elevation_gain_m, calories, avg_heart_rate)
    SELECT f.workout_id, w.distance, w.distance_unit, r.elevation_gain_m,
           CASE WHEN jsonb_typeof(w.details #> '{runkeeper,calories_burned}') = 'number'
                     AND (w.details #>> '{runkeeper,calories_burned}')::numeric >= 0
                THEN (w.details #>> '{runkeeper,calories_burned}')::numeric END,
           CASE WHEN jsonb_typeof(w.details #> '{runkeeper,average_heart_rate_bpm}') = 'number'
                     AND (w.details #>> '{runkeeper,average_heart_rate_bpm}')::numeric BETWEEN 20 AND 250
                THEN (w.details #>> '{runkeeper,average_heart_rate_bpm}')::numeric END
    FROM fitness.workouts f JOIN journal.workouts w USING (workout_id) LEFT JOIN journal.workout_routes r USING (workout_id)
    WHERE f.category = 'cardio'
    ON CONFLICT (workout_id) DO NOTHING;

    INSERT INTO fitness.workout_routes (workout_id, points, distance_km, elevation_gain_m, started_at, ended_at, file_name,
                                        file_asset_id, created_at)
    SELECT r.workout_id, r.points, r.distance_km, r.elevation_gain_m, r.started_at, r.ended_at, r.file_name, r.file_asset_id,
           r.created_at
    FROM journal.workout_routes r JOIN fitness.workout_cardio c USING (workout_id)
    ON CONFLICT (workout_id) DO NOTHING;

    INSERT INTO fitness.workout_strength (workout_id, position, lift, sets)
    SELECT l.workout_id, l.position, l.lift, l.sets
    FROM journal.workout_lifts l JOIN fitness.workouts f USING (workout_id) WHERE f.category = 'strength'
    ON CONFLICT DO NOTHING;

    INSERT INTO fitness.workout_hiit (workout_id, rounds, exercises_per_round, work_seconds, exercise_rest_seconds,
                                      round_rest_seconds)
    SELECT h.workout_id, h.rounds, h.exercises_per_round, h.work_seconds, h.exercise_rest_seconds, h.round_rest_seconds
    FROM journal.workout_circuits h JOIN fitness.workouts f USING (workout_id) WHERE f.category = 'hiit'
    ON CONFLICT (workout_id) DO NOTHING;

    -- New workouts number on from the moved ones.
    PERFORM setval(pg_get_serial_sequence('fitness.workouts', 'workout_id'),
                   COALESCE((SELECT MAX(workout_id) FROM fitness.workouts), 0) + 1, false);
END $$;

-- The old tables, and every view built on them (made again below, on fitness).
DROP VIEW IF EXISTS fitness.workout_sessions, core.daily_summary, journal.habit_days, journal.day_habits, journal.derived_habits,
                    health.goal_progress, health.weight_trend, health.weekly_workout_progress, health.daily_activity CASCADE;
DROP TABLE IF EXISTS journal.workout_routes, journal.workout_lifts, journal.workout_circuits, journal.workouts,
                     journal.workout_types CASCADE;

-- ── The view every screen reads: a workout with all of its facts ─────────────
CREATE VIEW fitness.workout_sessions AS
SELECT w.workout_id, w.workout_date, w.started_at, w.activity_type, t.label AS activity_label, w.category,
       k.label AS category_label, COALESCE(NULLIF(w.title, ''), t.label) AS name, w.title, w.minutes, w.note,
       t.counts_toward_goal, w.source, w.source_ref, w.details, w.created_at, w.updated_at,
       c.distance, c.distance_unit, c.distance_km, COALESCE(c.elevation_gain_m, r.elevation_gain_m) AS elevation_gain_m,
       c.calories, c.avg_heart_rate,
       r.workout_id IS NOT NULL AS has_route, r.started_at AS route_started_at,
       COALESCE((SELECT jsonb_agg(jsonb_strip_nulls(jsonb_build_object('lift', s.lift, 'sets', s.sets, 'reps', s.reps,
                                                                        'weight_lb', s.weight_lb)) ORDER BY s.position)
                 FROM fitness.workout_strength s WHERE s.workout_id = w.workout_id), '[]') AS lifts,
       (SELECT to_jsonb(h) - 'workout_id' - 'category' FROM fitness.workout_hiit h WHERE h.workout_id = w.workout_id) AS circuit
FROM fitness.workouts w
JOIN fitness.activity_types t USING (activity_type)
JOIN fitness.categories k ON k.category = w.category
LEFT JOIN fitness.workout_cardio c USING (workout_id)
LEFT JOIN fitness.workout_routes r USING (workout_id);

-- ── Health's views, as in 20_health.sql, on fitness ─────────────────────────
CREATE VIEW health.daily_activity AS
WITH days AS (
    SELECT workout_date AS day FROM fitness.workouts
    UNION SELECT meal_date FROM journal.meals
    UNION SELECT measured_on FROM health.body_measurements
    UNION SELECT drink_date FROM health.alcohol
    UNION SELECT log_date FROM health.daily_logs
    UNION SELECT entry_date FROM journal.entries
), workouts AS (
    SELECT w.workout_date AS day,
           COALESCE(SUM(w.minutes) FILTER (WHERE t.counts_toward_goal), 0) AS workout_minutes,
           COUNT(*) FILTER (WHERE t.counts_toward_goal) AS workout_sessions,
           COALESCE(SUM(w.minutes) FILTER (WHERE NOT t.counts_toward_goal), 0) AS dog_walk_minutes,
           -- By kind, from the base table; distance from the cardio facts.
           COALESCE(SUM(w.minutes) FILTER (WHERE w.category = 'cardio' AND t.counts_toward_goal), 0) AS cardio_minutes,
           COALESCE(SUM(w.minutes) FILTER (WHERE w.category = 'strength'), 0) AS strength_minutes,
           COALESCE(SUM(w.minutes) FILTER (WHERE w.category = 'hiit'), 0) AS hiit_minutes,
           COALESCE(SUM(w.minutes) FILTER (WHERE w.category = 'mobility'), 0) AS mobility_minutes,
           SUM(c.distance_km) FILTER (WHERE w.activity_type = 'run') AS run_km,
           SUM(c.distance_km) AS cardio_km
    FROM fitness.workouts w JOIN fitness.activity_types t USING (activity_type)
    LEFT JOIN fitness.workout_cardio c USING (workout_id)
    GROUP BY w.workout_date
), meals AS (
    SELECT meal_date AS day,
           COUNT(*) FILTER (WHERE status = 'eaten') AS meals_eaten,
           COUNT(*) FILTER (WHERE status = 'planned') AS meals_planned,
           SUM(calories) FILTER (WHERE status = 'eaten') AS meal_calories,
           SUM(calories) FILTER (WHERE status = 'planned') AS planned_calories,
           SUM(protein_g) FILTER (WHERE status = 'eaten') AS protein_g,
           SUM(carbs_g) FILTER (WHERE status = 'eaten') AS carbs_g,
           SUM(fat_g) FILTER (WHERE status = 'eaten') AS fat_g,
           SUM(fiber_g) FILTER (WHERE status = 'eaten') AS fiber_g
    FROM journal.meals GROUP BY meal_date
), drinks AS (
    SELECT drink_date AS day, SUM(containers) AS beers, SUM(standard_drinks) AS standard_drinks,
           SUM(calories) AS alcohol_calories
    FROM health.alcohol GROUP BY drink_date
), weigh_ins AS (
    SELECT measured_on AS day,
           COUNT(*) AS weigh_ins,
           COUNT(*) FILTER (WHERE is_morning) AS morning_weigh_ins,
           (ARRAY_AGG(value_lb ORDER BY measured_at NULLS FIRST, measurement_id))[1] AS first_weight,
           (ARRAY_AGG(value_lb ORDER BY measured_at DESC NULLS LAST, measurement_id DESC))[1] AS weight,
           'lb'::text AS weight_unit,
           (ARRAY_AGG(is_morning ORDER BY measured_at DESC NULLS LAST, measurement_id DESC))[1] AS weight_is_morning,
           MIN(value_lb) AS min_weight,
           MAX(value_lb) AS max_weight,
           ROUND(AVG(value_lb) FILTER (WHERE is_morning), 1) AS morning_weight
    FROM health.body_measurements WHERE metric = 'weight'
    GROUP BY measured_on
), profile AS (
    SELECT * FROM health.profile WHERE profile_id = 1
)
SELECT d.day,
       c.iso_weekday,
       c.week_start,
       COALESCE(w.workout_minutes, 0) AS workout_minutes,
       COALESCE(w.workout_sessions, 0) AS workout_sessions,
       COALESCE(w.dog_walk_minutes, 0) AS dog_walk_minutes,
       COALESCE(w.cardio_minutes, 0) AS cardio_minutes,
       COALESCE(w.strength_minutes, 0) AS strength_minutes,
       COALESCE(w.hiit_minutes, 0) AS hiit_minutes,
       COALESCE(w.mobility_minutes, 0) AS mobility_minutes,
       w.run_km, w.cardio_km,
       COALESCE(w.workout_minutes, 0) >= COALESCE(
           (SELECT target FROM health.goals WHERE metric = 'qualifying_workout_minutes'), 45) AS qualifying_workout_day,
       COALESCE(m.meals_eaten, 0) AS meals_eaten,
       COALESCE(m.meals_planned, 0) AS meals_planned,
       m.meal_calories, m.planned_calories, m.protein_g, m.carbs_g, m.fat_g, m.fiber_g,
       COALESCE(dr.beers, 0) AS beers,
       COALESCE(dr.standard_drinks, 0) AS standard_drinks,
       dr.alcohol_calories,
       CASE WHEN m.meal_calories IS NULL AND dr.alcohol_calories IS NULL THEN NULL
            ELSE COALESCE(m.meal_calories, 0) + COALESCE(dr.alcohol_calories, 0) END AS total_calories,
       (SELECT calorie_target FROM profile) AS calorie_target,
       COALESCE(l.nutrition_complete, false) AS nutrition_complete,
       COALESCE(dr.beers, 0) = 0
           OR (dr.beers < COALESCE((SELECT drink_boundary FROM profile), 3)
               AND c.iso_weekday = ANY (COALESCE((SELECT alcohol_days FROM profile), '{5,6,7}'::smallint[]))) AS alcohol_within_rules,
       COALESCE(wi.weigh_ins, 0) AS weigh_ins,
       COALESCE(wi.morning_weigh_ins, 0) AS morning_weigh_ins,
       wi.first_weight, wi.weight, wi.weight_unit, wi.weight_is_morning,
       wi.min_weight, wi.max_weight, wi.morning_weight,
       e.entry_date IS NOT NULL AS has_journal_entry
FROM days d
JOIN core.calendar c ON c.day = d.day
LEFT JOIN workouts w ON w.day = d.day
LEFT JOIN meals m ON m.day = d.day
LEFT JOIN drinks dr ON dr.day = d.day
LEFT JOIN weigh_ins wi ON wi.day = d.day
LEFT JOIN health.daily_logs l ON l.log_date = d.day
LEFT JOIN journal.entries e ON e.entry_date = d.day;

CREATE VIEW health.weekly_workout_progress AS
SELECT week_start,
       COUNT(*) FILTER (WHERE qualifying_workout_day) AS qualifying_days,
       SUM(workout_minutes) AS workout_minutes,
       SUM(dog_walk_minutes) AS dog_walk_minutes,
       SUM(beers) AS beers,
       SUM(standard_drinks) AS standard_drinks,
       COUNT(*) FILTER (WHERE NOT alcohol_within_rules) AS days_outside_alcohol_rules,
       (SELECT target FROM health.goals WHERE metric = 'workout_days_per_week') AS target_days,
       COUNT(*) FILTER (WHERE qualifying_workout_day)
           >= COALESCE((SELECT target FROM health.goals WHERE metric = 'workout_days_per_week'), 5) AS goal_met
FROM health.daily_activity
GROUP BY week_start;

-- Morning weigh-ins drive the trend, as in the Health tracker; others stay as references.
CREATE VIEW health.weight_trend AS
SELECT day, weigh_ins, weight, weight_unit, weight_is_morning, min_weight, max_weight, morning_weight,
       ROUND(AVG(morning_weight) OVER seven_days, 1) AS morning_avg_7d,
       ROUND(COALESCE(AVG(morning_weight) OVER seven_days, weight) * 0.45359237
             / NULLIF(((SELECT height_in FROM health.profile) * 0.0254) ^ 2, 0), 1) AS bmi
FROM health.daily_activity
WHERE weight IS NOT NULL
WINDOW seven_days AS (ORDER BY day RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW);

CREATE VIEW health.goal_progress AS
SELECT g.metric, g.target, g.unit, g.period, g.direction, c.current_value,
       CASE WHEN c.current_value IS NULL THEN NULL
            WHEN g.direction = 'at_least' THEN c.current_value >= g.target
            WHEN g.direction = 'below' THEN c.current_value < g.target
            ELSE c.current_value <= g.target END AS met
FROM health.goals g
LEFT JOIN LATERAL (
    SELECT CASE g.metric
        WHEN 'workout_days_per_week' THEN (
            SELECT qualifying_days::numeric FROM health.weekly_workout_progress
            WHERE week_start = date_trunc('week', current_date)::date)
        WHEN 'qualifying_workout_minutes' THEN (
            SELECT workout_minutes FROM health.daily_activity WHERE day = current_date)
        WHEN 'weight' THEN (
            SELECT COALESCE(morning_avg_7d, weight) FROM health.weight_trend ORDER BY day DESC LIMIT 1)
        WHEN 'bmi' THEN (
            SELECT bmi FROM health.weight_trend ORDER BY day DESC LIMIT 1)
        WHEN 'daily_calories' THEN (
            SELECT total_calories FROM health.daily_activity WHERE day = current_date)
        WHEN 'beers_per_day' THEN (
            SELECT beers FROM health.daily_activity WHERE day = current_date)
    END AS current_value
) c ON true;

-- ── Habits' views, as in 111_daily_habits.sql, on fitness ──────────────────
-- What the day's records say, for the habits that tick themselves (NULL: no record, or no rule).
CREATE VIEW journal.derived_habits AS
SELECT c.day, h.habit,
       CASE h.derived_from
           WHEN 'strength_workout' THEN EXISTS (SELECT 1 FROM fitness.workouts w
                                                WHERE w.workout_date = c.day AND w.category = 'strength')
           WHEN 'run_workout' THEN EXISTS (SELECT 1 FROM fitness.workouts w
                                           WHERE w.workout_date = c.day AND w.activity_type = 'run')
           WHEN 'alcohol' THEN EXISTS (SELECT 1 FROM health.alcohol a WHERE a.drink_date = c.day AND a.containers > 0)
       END AS done
FROM core.calendar c CROSS JOIN journal.habits h
WHERE h.derived_from IS NOT NULL;

-- Each day's habits, a row per habit for the screens: what the owner set, else what the day's records show.
CREATE VIEW journal.day_habits AS
SELECT c.day, h.habit, h.label, h.polarity, h.derived_from, h.position,
       COALESCE((to_jsonb(m) ->> h.habit)::boolean, d.done, false) AS done,
       CASE WHEN to_jsonb(m) ->> h.habit IS NOT NULL THEN 'manual' WHEN d.done THEN 'derived' ELSE 'none' END AS origin
FROM core.calendar c
CROSS JOIN journal.habits h
LEFT JOIN journal.daily_habits m ON m.day = c.day
LEFT JOIN journal.derived_habits d ON d.day = c.day AND d.habit = h.habit;

-- The same, a column per habit: every day with a habit set or ticked. Made from journal.habits, so a habit
-- added there (with its column) appears once journal.make_habit_days() runs again.
CREATE OR REPLACE FUNCTION journal.make_habit_days() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    cols text;
BEGIN
    SELECT string_agg(format('bool_or(done) FILTER (WHERE habit = %L) AS %I', habit, habit), ', ' ORDER BY position, habit)
    INTO cols FROM journal.habits;
    EXECUTE 'DROP VIEW IF EXISTS journal.habit_days';
    EXECUTE format($v$CREATE VIEW journal.habit_days AS
                      SELECT day, %s,
                             COUNT(*) FILTER (WHERE done AND polarity = 'build') AS habits_built,
                             COUNT(*) FILTER (WHERE done AND polarity = 'limit') AS habits_to_limit
                      FROM journal.day_habits
                      WHERE day IN (SELECT day FROM journal.daily_habits
                                    UNION SELECT workout_date FROM fitness.workouts
                                    UNION SELECT drink_date FROM health.alcohol)
                      GROUP BY day$v$, cols);
END $$;
SELECT journal.make_habit_days();

-- The cross-domain day, as in 111_daily_habits.sql: with habits from the day's own row and its records.
CREATE VIEW core.daily_summary AS
WITH active_days AS (
    SELECT day FROM health.daily_activity
    UNION SELECT day FROM journal.daily_habits
    UNION SELECT day FROM finance.spending
    UNION SELECT posted_on FROM finance.transactions
    UNION SELECT observed_on FROM garden.plant_observations
    UNION SELECT post_date FROM content.blog_posts
    UNION SELECT received_on FROM content.messages
), spend AS (
    SELECT day, SUM(amount) AS spending FROM finance.spending GROUP BY day
), income AS (
    SELECT t.posted_on AS day, SUM(-t.amount) AS income_received
    FROM finance.transactions t JOIN finance.movement_types mt USING (movement_type)
    WHERE mt.flow = 'income' GROUP BY t.posted_on
)
SELECT c.day, c.iso_weekday, c.week_start, c.month_start,
       e.entry_id IS NOT NULL AS has_journal_entry,
       COALESCE(h.habits_built, 0) AS habits_built,
       COALESCE(h.habits_to_limit, 0) AS habits_to_limit,
       COALESCE(a.workout_minutes, 0) AS workout_minutes,
       COALESCE(a.qualifying_workout_day, false) AS qualifying_workout_day,
       a.total_calories,
       a.calorie_target,
       COALESCE(a.beers, 0) AS beers,
       a.weight,
       COALESCE(s.spending, 0) AS spending,
       COALESCE(i.income_received, 0) AS income_received,
       (SELECT COUNT(*) FROM garden.plant_observations o WHERE o.observed_on = c.day) AS garden_observations,
       (SELECT COUNT(*) FROM content.blog_posts p WHERE p.post_date = c.day AND p.published) AS posts_published
FROM active_days d
JOIN core.calendar c ON c.day = d.day
LEFT JOIN journal.entries e ON e.entry_date = c.day
LEFT JOIN LATERAL (SELECT COUNT(*) FILTER (WHERE dh.done AND dh.polarity = 'build') AS habits_built,
                          COUNT(*) FILTER (WHERE dh.done AND dh.polarity = 'limit') AS habits_to_limit
                   FROM journal.day_habits dh WHERE dh.day = c.day) h ON true
LEFT JOIN health.daily_activity a ON a.day = c.day
LEFT JOIN spend s ON s.day = c.day
LEFT JOIN income i ON i.day = c.day;
